spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieclub
    username: root
    password: root
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:///E:/JavaStart/Projekty/movieclub/uploads/
app:
  storage:
    location: E:/JavaStart/Projekty/movieclub/uploads/